In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Q1: Difference in the data type of list_ and array_list

In [2]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


Q2: Data type of each element in list_ and array_list

In [3]:
# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3: Difference in data type after changing array_list to integers

In [4]:
# Change array_list to integer type
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_ and array_list
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4: Characteristics of num_array (shape and size)

In [5]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Print shape and size
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


Q5: Create a
3×3 matrix of zeros


In [6]:
# Create a 3x3 matrix of zeros
zeros_matrix = np.zeros((3, 3))
print("3x3 matrix of zeros:")
print(zeros_matrix)


3x3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6: Create an identity matrix of shape
5
×
5


In [7]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 identity matrix:")
print(identity_matrix)


5x5 identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
